version: "3"

services:
  producty:
    container_name: producty
    image: node:16-alpine

    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    entrypoint: ["sh", "-c", "npm install && npm run dev"]
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules/
      - /app/.next
    env_file:
      - .env
    platform: linux/x86_64
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres-data:/var/lib/postgresql/data
  prisma:
    build: .
    command: npx prisma migrate deploy
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/database
    volumes:
      - .:/app
      - node_modules:/app/node_modules
volumes:
  postgres-data:
  node_modules:
